const states = [
  { id: 12, name: "Acre", initials: "AC" },
  { id: 27, name: "Alagoas", initials: "AL" },
  { id: 13, name: "Amazonas", initials: "AM" },
  { id: 16, name: "Amapá", initials: "AP" },
  { id: 29, name: "Bahia", initials: "BA" },
  { id: 23, name: "Ceará", initials: "CE" },
  { id: 53, name: "Distrito Federal", initials: "DF" },
  { id: 32, name: "Espírito Santo", initials: "ES" },
  { id: 52, name: "Goiás", initials: "GO" },
  { id: 21, name: "Maranhão", initials: "MA" },
  { id: 31, name: "Minas Gerais", initials: "MG" },
  { id: 50, name: "Mato Grosso do Sul", initials: "MS" },
  { id: 51, name: "Mato Grosso", initials: "MT" },
  { id: 15, name: "Pará", initials: "PA" },
  { id: 25, name: "Paraíba", initials: "PB" },
  { id: 26, name: "Pernambuco", initials: "PE" },
  { id: 22, name: "Piauí", initials: "PI" },
  { id: 41, name: "Paraná", initials: "PR" },
  { id: 33, name: "Rio de Janeiro", initials: "RJ" },
  { id: 24, name: "Rio Grande do Norte", initials: "RN" },
  { id: 11, name: "Rondônia", initials: "RO" },
  { id: 14, name: "Roraima", initials: "RR" },
  { id: 43, name: "Rio Grande do Sul", initials: "RS" },
  { id: 42, name: "Santa Catarina", initials: "SC" },
  { id: 28, name: "Sergipe", initials: "SE" },
  { id: 35, name: "São Paulo", initials: "SP" },
  { id: 17, name: "Tocantins", initials: "TO" },
];

module.exports = states;
